server {
    listen 80;
    listen [::]:80;
    server_name wantmeseen.com www.wantmeseen.com wantmeseen.de www.wantmeseen.de;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/letsencrypt;
        default_type text/plain;
    }

    location / {
        return 302 https://tu1nz.com/adult/;
    }
}
