user www-data;
worker_processes 1;
pid /opt/tu1nz_repos/control/nginx/validation.pid;
error_log stderr;

events {
    worker_connections 64;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    access_log off;
    include /etc/nginx/conf.d/*.conf;

    include /opt/tu1nz_repos/control/nginx/current/api.mychatbuddy.dev;
}
